# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d516f3c82b48d59fed9d1ab3c23bc0ff27f211158ffc261a6079d62c9f42d4833ef576e0af15db5448d5190bf8f96674bc4cd29a80269c0fb76a3e28d2051922

test:
  secret_key_base: 54b6e640520f88398f35dd946a9e8e335b068093ea2edf2e984a2185c66df844df98464e11cbf45cd71e001ccff2fe655c93af8bcd4c244cf49828b9af0251db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
